import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'OrthoAlign Case Management API',
      version: '1.0.0',
      description: 'A comprehensive case management system for dental practices with workflow tracking, role-based access control, and payment processing.',
      contact: {
        name: 'API Support',
        email: 'support@orthoalign.com',
      },
    },
    servers: [
      {
        url: 'http://localhost:3000',
        description: 'Development server',
      },
      {
        url: 'https://api.orthoalign.com',
        description: 'Production server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Enter your JWT token',
        },
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clx123abc' },
            email: { type: 'string', format: 'email', example: 'user@example.com' },
            name: { type: 'string', example: 'John Doe' },
            role: { type: 'string', enum: ['CLIENT', 'ADMIN', 'EMPLOYEE'], example: 'CLIENT' },
            employeeType: { type: 'string', enum: ['DESIGNER', 'QC', 'BOTH'], nullable: true, example: null },
            gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'], nullable: true, example: 'MALE' },
            region: { type: 'string', nullable: true, example: 'North America' },
            phone: { type: 'string', nullable: true, example: '+1-234-567-8900' },
            website: { type: 'string', nullable: true, example: 'https://example.com' },
            businessAddress: { type: 'string', nullable: true, example: '123 Main St, City, State 12345' },
            hearAboutUs: { type: 'string', nullable: true, example: 'Google Search' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Patient: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clx456def' },
            name: { type: 'string', example: 'Jane Smith' },
            gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'], nullable: true, example: 'FEMALE' },
            dateOfBirth: { type: 'string', format: 'date', nullable: true, example: '1990-01-15' },
            address: { type: 'string', nullable: true, example: '123 Main St, New York, NY 10001' },
            notes: { type: 'string', nullable: true, example: 'Regular patient' },
            createdById: { type: 'string', example: 'clx123abc' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Case: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clx789ghi' },
            patientId: { type: 'string', example: 'clx456def' },
            createdById: { type: 'string', example: 'clx123abc' },
            status: {
              type: 'string',
              enum: [
                'PENDING_PAYMENT',
                'PENDING_APPROVAL',
                'OPENED',
                'ASSIGNED',
                'IN_DESIGN',
                'PENDING_QC',
                'QC_REJECTED',
                'PENDING_CLIENT_REVIEW',
                'CLIENT_REJECTED',
                'APPROVED',
                'CANCELLED',
              ],
              example: 'PENDING_PAYMENT',
            },
            designerId: { type: 'string', nullable: true, example: null },
            qcId: { type: 'string', nullable: true, example: null },
            notes: { type: 'string', nullable: true, example: 'Upper arch alignment' },
            refinementCount: { type: 'number', example: 0, description: 'Number of times case was sent back for refinement' },
            paymentProofUrl: { type: 'string', nullable: true, example: 'https://orthoalign.s3.ap-southeast-1.amazonaws.com/cases/clx789ghi/payment-proof/receipt.pdf' },
            submittedAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Payment: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clx111jkl' },
            caseId: { type: 'string', example: 'clx789ghi' },
            amount: { type: 'number', format: 'float', example: 1500.0 },
            status: { type: 'string', enum: ['PENDING', 'COMPLETED', 'FAILED'], example: 'PENDING' },
            externalId: { type: 'string', nullable: true, example: 'stripe_pi_123' },
            paidAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        CaseWorkflowLog: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clx222mno' },
            caseId: { type: 'string', example: 'clx789ghi' },
            fromStatus: { type: 'string', nullable: true, example: 'ASSIGNED' },
            toStatus: { type: 'string', example: 'IN_DESIGN' },
            performedById: { type: 'string', example: 'clx123abc' },
            note: { type: 'string', nullable: true, example: 'Started working on case' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        CaseFile: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clxfile123' },
            caseId: { type: 'string', example: 'clx789ghi' },
            category: { type: 'string', enum: ['SCAN', 'PHOTO', 'XRAY', 'PRODUCTION', 'OTHER'], example: 'SCAN' },
            fileName: { type: 'string', example: 'patient_scan_001.jpg' },
            fileUrl: { type: 'string', example: 'https://orthoalign.s3.ap-southeast-1.amazonaws.com/cases/clx789ghi/scan/1234567890-patient_scan_001.jpg' },
            fileSize: { type: 'number', example: 2048576, description: 'File size in bytes' },
            mimeType: { type: 'string', example: 'image/jpeg' },
            uploadedAt: { type: 'string', format: 'date-time' },
          },
        },
        PrescriptionInput: {
          type: 'object',
          required: ['chiefComplaint'],
          properties: {
            chiefComplaint: { type: 'string', example: 'Patient wants to improve alignment and bite', minLength: 10 },
            durationRecommended: { type: 'boolean', default: true },
            durationLimitSteps: { type: 'integer', example: 20, nullable: true },
            upperMidlinePosition: { type: 'string', enum: ['CENTERED', 'SHIFTED_RIGHT', 'SHIFTED_LEFT'], default: 'CENTERED' },
            upperMidlineShiftMm: { type: 'number', example: 2.5, nullable: true },
            lowerMidlinePosition: { type: 'string', enum: ['CENTERED', 'SHIFTED_RIGHT', 'SHIFTED_LEFT'], default: 'CENTERED' },
            lowerMidlineShiftMm: { type: 'number', example: 1.5, nullable: true },
            canineRelationshipRight: { type: 'string', example: 'Class I', nullable: true },
            canineRelationshipLeft: { type: 'string', example: 'Class I', nullable: true },
            molarRelationshipRight: { type: 'string', example: 'Class II', nullable: true },
            molarRelationshipLeft: { type: 'string', example: 'Class I', nullable: true },
            treatUpperArch: { type: 'boolean', default: true },
            treatLowerArch: { type: 'boolean', default: true },
            upperMidlineGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            lowerMidlineGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            overjetGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            overbiteGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            archFormGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            canineRelationshipGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'IMPROVE' },
            molarRelationshipGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'MAINTAIN' },
            posteriorRelationshipGoal: { type: 'string', enum: ['MAINTAIN', 'IMPROVE', 'IDEALIZE'], default: 'MAINTAIN' },
            iprOption: { type: 'string', enum: ['YES', 'NO', 'ONLY_IF_NEEDED'], default: 'ONLY_IF_NEEDED' },
            engagersOption: { type: 'string', enum: ['YES', 'NO', 'ONLY_IF_NEEDED'], default: 'ONLY_IF_NEEDED' },
            proclineOption: { type: 'string', enum: ['YES', 'NO', 'ONLY_IF_NEEDED'], default: 'ONLY_IF_NEEDED' },
            expandOption: { type: 'string', enum: ['YES', 'NO', 'ONLY_IF_NEEDED'], default: 'ONLY_IF_NEEDED' },
            distalizeOption: { type: 'string', enum: ['YES', 'NO', 'ONLY_IF_NEEDED'], default: 'ONLY_IF_NEEDED' },
            avoidEngagersTeeth: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 32 }, example: [8, 9, 24, 25] },
            extractTeeth: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 32 }, example: [1, 16, 17, 32] },
            leaveSpacesTeeth: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 32 }, example: [] },
            doNotMoveTeeth: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 32 }, example: [] },
            includeRetainer: { type: 'boolean', default: true },
            additionalInstructions: { type: 'string', example: 'Please focus on improving upper arch first', nullable: true },
          },
        },
        Prescription: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clxpres123' },
            caseId: { type: 'string', example: 'clx789ghi' },
            chiefComplaint: { type: 'string', example: 'Patient wants to improve alignment and bite' },
            durationRecommended: { type: 'boolean', example: true },
            durationLimitSteps: { type: 'integer', example: null, nullable: true },
            upperMidlinePosition: { type: 'string', enum: ['CENTERED', 'SHIFTED_RIGHT', 'SHIFTED_LEFT'], example: 'CENTERED' },
            upperMidlineShiftMm: { type: 'number', example: null, nullable: true },
            lowerMidlinePosition: { type: 'string', enum: ['CENTERED', 'SHIFTED_RIGHT', 'SHIFTED_LEFT'], example: 'CENTERED' },
            lowerMidlineShiftMm: { type: 'number', example: null, nullable: true },
            canineRelationshipRight: { type: 'string', example: 'Class I', nullable: true },
            canineRelationshipLeft: { type: 'string', example: 'Class I', nullable: true },
            molarRelationshipRight: { type: 'string', example: 'Class II', nullable: true },
            molarRelationshipLeft: { type: 'string', example: 'Class I', nullable: true },
            treatUpperArch: { type: 'boolean', example: true },
            treatLowerArch: { type: 'boolean', example: true },
            upperMidlineGoal: { type: 'string', example: 'IMPROVE' },
            lowerMidlineGoal: { type: 'string', example: 'IMPROVE' },
            overjetGoal: { type: 'string', example: 'IMPROVE' },
            overbiteGoal: { type: 'string', example: 'IMPROVE' },
            archFormGoal: { type: 'string', example: 'IMPROVE' },
            canineRelationshipGoal: { type: 'string', example: 'IMPROVE' },
            molarRelationshipGoal: { type: 'string', example: 'MAINTAIN' },
            posteriorRelationshipGoal: { type: 'string', example: 'MAINTAIN' },
            iprOption: { type: 'string', example: 'ONLY_IF_NEEDED' },
            engagersOption: { type: 'string', example: 'ONLY_IF_NEEDED' },
            proclineOption: { type: 'string', example: 'ONLY_IF_NEEDED' },
            expandOption: { type: 'string', example: 'ONLY_IF_NEEDED' },
            distalizeOption: { type: 'string', example: 'ONLY_IF_NEEDED' },
            avoidEngagersTeeth: { type: 'array', items: { type: 'integer' }, example: [8, 9, 24, 25] },
            extractTeeth: { type: 'array', items: { type: 'integer' }, example: [] },
            leaveSpacesTeeth: { type: 'array', items: { type: 'integer' }, example: [] },
            doNotMoveTeeth: { type: 'array', items: { type: 'integer' }, example: [] },
            includeRetainer: { type: 'boolean', example: true },
            additionalInstructions: { type: 'string', example: null, nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CaseComment: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clxcomment123' },
            caseId: { type: 'string', example: 'clx789ghi' },
            userId: { type: 'string', example: 'clx123abc' },
            comment: { type: 'string', example: 'Please review the alignment on tooth #8' },
            isInternal: { type: 'boolean', default: false, description: 'If true, comment is only visible to employees (QC/Designer)' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            user: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                email: { type: 'string' },
                role: { type: 'string', enum: ['CLIENT', 'ADMIN', 'EMPLOYEE'] },
              },
            },
            attachments: {
              type: 'array',
              items: {
                $ref: '#/components/schemas/CommentAttachment',
              },
            },
          },
        },
        CommentAttachment: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clxattach123' },
            commentId: { type: 'string', example: 'clxcomment123' },
            fileName: { type: 'string', example: 'tooth_8_detail.jpg' },
            fileUrl: { type: 'string', example: 'https://orthoalign.s3.ap-southeast-1.amazonaws.com/cases/clx789ghi/comments/clxcomment123/1234567890-tooth_8_detail.jpg' },
            fileSize: { type: 'number', example: 1024567 },
            mimeType: { type: 'string', example: 'image/jpeg' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        CaseProductionUrl: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'clxurl123' },
            caseId: { type: 'string', example: 'clx789ghi' },
            url: { type: 'string', format: 'uri', example: 'https://drive.google.com/file/d/abc123/view' },
            description: { type: 'string', nullable: true, example: 'Final 3D model files' },
            addedById: { type: 'string', example: 'clxdesigner123' },
            createdAt: { type: 'string', format: 'date-time' },
            addedBy: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                email: { type: 'string' },
              },
            },
          },
        },
        Error: {
          type: 'object',
          properties: {
            error: { type: 'string', example: 'Error message' },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
    tags: [
      {
        name: 'Authentication',
        description: 'User authentication and registration',
      },
      {
        name: 'Dashboard',
        description: 'Client dashboard statistics',
      },
      {
        name: 'Patients',
        description: 'Patient management',
      },
      {
        name: 'Cases',
        description: 'Case management and workflow',
      },
      {
        name: 'Case Files',
        description: 'File upload and management for cases',
      },
      {
        name: 'Prescriptions',
        description: 'Case prescription management (Step 2 - Treatment instructions)',
      },
      {
        name: 'Case Submission',
        description: 'Case submission workflow (Step 3 - Payment proof & submission)',
      },
      {
        name: 'Case Comments',
        description: 'Case comments with file attachments',
      },
      {
        name: 'Production (Designer)',
        description: 'Designer production file and URL management',
      },
      {
        name: 'Employee',
        description: 'Employee case viewing and management',
      },
      {
        name: 'Designer Actions',
        description: 'Designer workflow actions (submit to QC)',
      },
      {
        name: 'QC Review',
        description: 'QC case approval and rejection workflow',
      },
      {
        name: 'Payments',
        description: 'Payment processing and tracking',
      },
      {
        name: 'Users',
        description: 'User management (Admin only)',
      },
    ],
  },
  apis: ['./src/routes/*.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
